version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kingcodeUser
      - POSTGRES_PASSWORD=kingcodePass
      - POSTGRES_DB=kingcodeDB
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5050:80'
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
#      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1